services:
  postgres:
    image: postgres:16.4-alpine
    container_name: gateway-postgres
    restart: "no"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: gateway-adminer
    restart: "no"
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: